version: '3.9'

services:
  # Install pipenv and dependencies
  pipenv:
    container_name: prode-pipenv
    image: prode/backend
    build:
      dockerfile: ./server/Dockerfile
      target: installer # "Just run the build until this step"
    command: pipenv install
    volumes:
      - ./server:/app

  django:
    image: prode/backend
    container_name: prode-server
    ports:
      - 8000:8000
    depends_on:
      pipenv:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    command: pipenv run python manage.py runserver 0:8000
    volumes:
      - ./server:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=prode
      - DATABASE_NAME=prode
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=

  postgres:
    container_name: prode-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prode
    ports:
      - "5432:5432"

  # Install frontend dependencies
  npm:
    image: node:18-alpine
    container_name: prode-npm
    working_dir: /app
    volumes:
      - ./client:/app
    command: npm install

  react:
    container_name: prode-app
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
    depends_on:
      npm:
        condition: service_completed_successfully
      django:
        condition: service_started
    command: npm run dev -- --host
