version: '3.9'

services:
  backend:
    build:
      context: ./server
    depends_on:
      db:
        condition: service_started
    environment:
      - DEBUG=False
      - SECRET_KEY=prode
      - DATABASE_NAME=prode
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pipenv run python manage.py migrate --noinput &&
      pipenv run python manage.py collectstatic --noinput --clear &&
      pipenv run gunicorn --bind 0.0.0.0:8000 prode.wsgi"
    volumes:
      - static_volume:/app/static # collectstatic folder
      - media_volume:/app/media # media folder
    expose:
      - 8000

  backend-nginx:
    build:
      context: ./server-nginx
    ports:
      - 9000:80
    volumes:
      - static_volume:/usr/share/nginx/html/static # collectstatic folder
      - media_volume:/usr/share/nginx/html/media # media folder

  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prode
    ports:
      - "5432:5432"

  frontend:
    build:
      args:
        - BACKEND_URL=http://localhost:9000
      context: ./client
    network_mode: "host"
    depends_on:
      backend:
        condition: service_started

volumes:
  pg_data:
  # Shared between nginx-backend and backend
  static_volume:
  media_volume:
