version: '3.9'

services:
  django:
    container_name: prode-django
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_started
    environment:
      - DEBUG=True
      - SECRET_KEY=prode
      - DATABASE_NAME=prode
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=
      - PYTHONUNBUFFERED=1

  postgres:
    container_name: prode-postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prode
    ports:
      - "5432:5432"

  react:
    container_name: prode-react
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - BACKEND_URL=http://django:8000/
    depends_on:
      django:
        condition: service_started
