# Generated by Django 3.2.16 on 2022-12-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('match', 'participant')},
        ),
    ]
