# Generated by Django 3.2.16 on 2022-12-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221217_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(blank=True, default=None, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
